### ISSUE TITLE
Criar RestController para listagem de um cliente service.

### ISSUE THREAD

**Issue by Taisaferreiraflavio** [Taisaferreiraflavio/helpr#1]
- [x] #2
- [x] #3
- [x] Criar métodos para o end point de REstController
- [x] Vincular os repositórios de clientes
- [x] Executar testes de end point no postman

**Comment by soulcode-acad** [comment]
Trabalho entregue com maestria Taísa faltou alguns detalhes como analise e padronização das nomenclaturas e as entregas estão perfeitas mas esqueceu de limpar as branchs de resto impecável.
![image](https://user-images.githubusercontent.com/100297907/172858538-91afff35-1352-4a34-b152-7b1f1f556992.png)
